### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by gramss** [MarcToussaint/botop#1]
Hey there, really impressive demo I just witnessed on twitter.. 🤩

Out of commercial but also research perspective I highly recommend you to add a license that makes the usage of your code absolutely clear.
If I could wish for something -> BSD 3 (can be used for everything research and commercially and you are not liable nor provide warranty for the code, while everyone needs to cite your work if used).. regardless of your choice, please just add some license rather soon. I am not aware what is the default license scenario for blank code on GitHub.

Besides that -> how can I use your very impressive code in a modular setup. Let's say for example ROS2? 😄

**Comment by MarcToussaint** [comment]
Thanks, Florian, for the note! I added the MIT License (as the underlying rai code hase).

We used to use ROS a lot (with the PR2) some 15-10 yrs back -- and rai still has some contact points (default ways to wrap a data structure into a muxtex that automatically subscribes/publishes to ROS (roscom.h)). BUT I stopped using ROS altogether :-)
